# Generated by Django 5.1.7 on 2025-03-19 21:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DogAdoptionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="İlan Başlığı"),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="Açıklama")),
                ("breed", models.CharField(max_length=50, verbose_name="Köpek Irkı")),
                ("age", models.IntegerField(verbose_name="Köpek Yaşı")),
                ("location", models.CharField(max_length=100, verbose_name="Konum")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "dog_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dog_images/",
                        verbose_name="Köpek Fotoğrafı",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sahiplenen Kullanıcı",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="AdoptionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_author",
                    models.CharField(max_length=50, verbose_name="Yorum Sahibi"),
                ),
                ("comment_content", models.TextField(verbose_name="Yorum")),
                (
                    "comment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yorum Tarihi"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="getdogco.dogadoptionpost",
                        verbose_name="İlan",
                    ),
                ),
            ],
            options={
                "ordering": ["-comment_date"],
            },
        ),
    ]
