# Generated by Django 5.1.7 on 2025-04-03 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("getdogco", "0005_adoptioncomment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("contact_info", models.CharField(max_length=255)),
                ("location_info", models.CharField(max_length=255)),
                ("had_pets_before", models.CharField(max_length=10)),
                ("work_hours", models.CharField(blank=True, max_length=100)),
                ("has_allergy", models.CharField(blank=True, max_length=10)),
                ("motivation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="getdogco.dogadoptionpost",
                    ),
                ),
            ],
        ),
    ]
