# Generated by Django 5.1.7 on 2025-04-04 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("getdogco", "0007_application_is_read_application_status_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
